### ISSUE TITLE
Error on pimatic load

### ISSUE THREAD

**Issue by muldy** [josecastroleon/pimatic-ble#1]
Hi!

I'm trying to get pimatic-ble running on a raspberry pi 2 with no sucess:

21:35:07.366 [pimatic] info: Loading plugin: "pimatic-ble" (0.8.0)
21:35:07.383 [pimatic] error: Cannot find module 'convict'
21:35:07.417 [pimatic] debug: Error: Cannot find module 'convict'
21:35:07.417 [pimatic] debug:>    at Function.Module._resolveFilename (module.js:325:15)
21:35:07.417 [pimatic] debug:>    at Function.Module._load (module.js:276:25)
21:35:07.417 [pimatic] debug:>    at Module.require (module.js:353:17)
21:35:07.417 [pimatic] debug:>    at Object.env.require (/home/pi/pimatic-app/node_modules/pimatic/startup.coffee:25:28)
21:35:07.417 [pimatic] debug:>    at module.exports (/home/pi/pimatic-app/node_modules/pimatic-ble/ble.coffee:3:17)
21:35:07.417 [pimatic] debug:>    at PluginManager.loadPlugin (/home/pi/pimatic-app/node_modules/pimatic/lib/plugins.coffee:83:16)
21:35:07.417 [pimatic] debug:>    at /home/pi/pimatic-app/node_modules/pimatic/lib/plugins.coffee:477:25
21:35:07.417 [pimatic] debug:>    at tryCatcher (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/release/util.js:16:23)
21:35:07.417 [pimatic] debug:>    at Promise._settlePromiseFromHandler (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/release/promise.js:503:31)
21:35:07.417 [pimatic] debug:>    at Promise._settlePromise (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/release/promise.js:560:18)
21:35:07.417 [pimatic] debug:>    at Promise._settlePromiseCtx (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/release/promise.js:597:10)
21:35:07.417 [pimatic] debug:>    at Async._drainQueue (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/release/async.js:131:12)
21:35:07.417 [pimatic] debug:>    at Async._drainQueues (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/release/async.js:136:10)
21:35:07.417 [pimatic] debug:>    at Immediate.Async.drainQueues [as _onImmediate](/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/release/async.js:16:14)
21:35:07.417 [pimatic] debug:>    at processImmediate [as _immediateCallback](timers.js:383:17)

**Comment by muldy** [comment]
Removed the requirement for convict (was not used)

but got:
noble warning: adapter does not support Bluetooth Low Energy (BLE, Bluetooth Smart).
               Try to run with environment variable:
               [sudo] NOBLE_HCI_DEVICE_ID=x node ...

So, a special bluetooth adapter is needed? for bluetooth low energy devices?
